Update cicd.yml final i hope

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -21,6 +21,11 @@ jobs:
     - name: run make install
       run: sudo make install
 
+    - name: Verify Install
+      run: |
+        make install || { echo " Failed Installation"; exit 1; }
+      
+
     
       
 
